[versions]
minecraft = "26.1.2"
neoForge = "26.1.2.76"
lombokPlugin = "9.2.0"
lombok = "1.18.44"
modDevGradle = "2.0.140"
anvillib = "2.0.0+snapshot.472"
anvilcraft = "1.6.0+snapshot.1912"
jts = "1.20.0"

[libraries]
jts = { group = 'org.locationtech.jts', name = 'jts-core', version.ref = "jts" }
anvillib = { group = "dev.anvilcraft.lib", name = "anvillib-neoforge-26.1", version.ref = "anvillib" }
anvilcraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-26.1.2", version.ref = "anvilcraft" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
